image: node:lts

pipelines:
  branches:
    develop:
      - step:
          name: Copy static files
          image: google/cloud-sdk:latest
          script:
            # Convert key base64 to JSON file
            - echo "$DEPLOYER_KEY_DEV" >> _pipe_key.txt
            - base64 -d _pipe_key.txt > _pipe_key.json
            # autentica o Cloud SDK
            # - gcloud auth activate-service-account --key-file ./_pipe_key.json
            # copia os arquivos estaticos
            # - gsutil cp -r gs://${PROJECT_ID}.appspot.com/static ./src/
          artifacts:
            - _pipe_key.json
            # - src/static/**
      - step:
          name: Build and deploy
          deployment: develop
          script:
            - cd functions/
            # Install functions dependencies
            - yarn install
            # Setup environment variables in functions
            - cd ../
            # Install front-end dependencies
            - yarn install
            # Download sdk configs
            - GOOGLE_APPLICATION_CREDENTIALS=./_pipe_key.json yarn download-firebase-config -P $PROJECT_ID
            # Build front-end
            - yarn build
            # Deploy to Firebase
            - pipe: atlassian/firebase-deploy:1.3.0
              variables:
                KEY_FILE: $DEPLOYER_KEY_DEV
                PROJECT_ID: $PROJECT_ID
    master:
      - step:
          name: Copy static files
          image: google/cloud-sdk:latest
          script:
            # Convert key base64 to JSON file
            - echo "$DEPLOYER_KEY_PROD" >> _pipe_key.txt
            - base64 -d _pipe_key.txt > _pipe_key.json
            # autentica o Cloud SDK
            # - gcloud auth activate-service-account --key-file ./_pipe_key.json
            # copia os arquivos estaticos
            # - gsutil cp -r gs://${PROJECT_ID}.appspot.com/static ./src/
          artifacts:
            - _pipe_key.json
            # - src/static/**
      - step:
          name: Build and deploy
          deployment: production
          script:
            - cd functions/
            # Install functions dependencies
            - yarn install
            # Setup environment variables in functions
            - cd ../
            # Install front-end dependencies
            - yarn install
            # Download sdk configs
            - GOOGLE_APPLICATION_CREDENTIALS=./_pipe_key.json yarn download-firebase-config -P $PROJECT_ID
            # Build front-end
            - yarn build
            # Deploy to Firebase
            - pipe: atlassian/firebase-deploy:1.3.0
              variables:
                KEY_FILE: $DEPLOYER_KEY_PROD
                PROJECT_ID: $PROJECT_ID